import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <link rel="stylesheet" href="assets/css/alori.css" />
        <link rel="stylesheet" href="assets/css/alori-responsive.css" />
        {/* <!-- fonts --> */}
        <link
          href="https://fonts.googleapis.com/css2?family=Domine:wght@400;500;600;700&amp;family=Kumbh+Sans:wght@400;500;600;700;800&amp;display=swap"
          rel="stylesheet" />
        <link rel="stylesheet" href="assets/vendors/bootstrap/css/bootstrap.min.css" />
        <link rel="stylesheet" href="assets/vendors/animate/animate.min.css" />
        <link rel="stylesheet" href="assets/vendors/animate/custom-animate.css" />
        <link rel="stylesheet" href="assets/vendors/fontawesome/css/all.min.css" />
        <link rel="stylesheet" href="assets/vendors/jarallax/jarallax.css" />
        <link rel="stylesheet" href="assets/vendors/jquery-magnific-popup/jquery.magnific-popup.css" />
        <link rel="stylesheet" href="assets/vendors/nouislider/nouislider.min.css" />
        <link rel="stylesheet" href="assets/vendors/nouislider/nouislider.pips.css" />
        <link rel="stylesheet" href="assets/vendors/odometer/odometer.min.css" />
        <link rel="stylesheet" href="assets/vendors/swiper/swiper.min.css" />
        <link rel="stylesheet" href="assets/vendors/icomoon-icons/style.css" />
        <link rel="stylesheet" href="assets/vendors/tiny-slider/tiny-slider.min.css" />
        <link rel="stylesheet" href="assets/vendors/reey-font/stylesheet.css" />
        <link rel="stylesheet" href="assets/vendors/owl-carousel/owl.carousel.min.css" />
        <link rel="stylesheet" href="assets/vendors/owl-carousel/owl.theme.default.min.css" />
        <link rel="stylesheet" href="assets/vendors/twentytwenty/twentytwenty.css" />
        {/* <!-- favicons Icons --> */}
        <link rel="apple-touch-icon" sizes="180x180" href="assets/images/favicons/apple-touch-icon.png" />
        <link rel="icon" type="image/png" sizes="32x32" href="assets/images/favicons/favicon-32x32.png" />
        <link rel="icon" type="image/png" sizes="16x16" href="assets/images/favicons/favicon-16x16.png" />
        <link rel="manifest" href="assets/images/favicons/site.webmanifest" />

        <script src="assets/vendors/jquery/jquery-3.5.1.min.js"></script>
        <script src="assets/vendors/bootstrap/js/bootstrap.bundle.min.js"></script>
        <script src="assets/vendors/jarallax/jarallax.min.js"></script>
        <script src="assets/vendors/jquery-ajaxchimp/jquery.ajaxchimp.min.js"></script>
        <script src="assets/vendors/jquery-appear/jquery.appear.min.js"></script>
        <script src="assets/vendors/jquery-circle-progress/jquery.circle-progress.min.js"></script>
        <script src="assets/vendors/jquery-magnific-popup/jquery.magnific-popup.min.js"></script>
        <script src="assets/vendors/jquery-validate/jquery.validate.min.js"></script>
        <script src="assets/vendors/nouislider/nouislider.min.js"></script>

        <script src="assets/vendors/odometer/odometer.min.js"></script>
        <script src="assets/vendors/swiper/swiper.min.js"></script>
        <script src="assets/vendors/tiny-slider/tiny-slider.min.js"></script>
        <script src="assets/vendors/wnumb/wNumb.min.js"></script>
        <script src="assets/vendors/wow/wow.js"></script>
        <script src="assets/vendors/isotope/isotope.js"></script>
        <script src="assets/vendors/countdown/countdown.min.js"></script>
        <script src="assets/vendors/owl-carousel/owl.carousel.min.js"></script>
        <script src="assets/vendors/twentytwenty/twentytwenty.js"></script>
        <script src="assets/vendors/twentytwenty/jquery.event.move.js"></script>
        <script src="assets/vendors/parallax/parallax.min.js"></script>
        <script src="assets/vendors/nice-select/jquery.nice-select.min.js"></script>
        <script src="assets/vendors/progress-bar/knob.js"></script>
        <script src="assets/vendors/tilt.js/tilt.jquery.js"></script>


        <script src="http://maps.google.com/maps/api/js?key=AIzaSyATY4Rxc8jNvDpsK8ZetC7JyN4PFVYGCGM"></script>

        {/* <!-- template js --> */}
        <script src="assets/js/alori.js"></script>
      </head>
      <body className={inter.className}>{children}</body>
    </html>
  )
}
